apiVersion: v1
kind: Service
metadata:
  labels:
    service: ducta11-kubernetes-udagram-reverseproxy
  name: ducta11-kubernetes-udagram-reverseproxy-svc
spec:
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
  selector:
    service: ducta11-kubernetes-udagram-reverseproxy