apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ducta11-kubernetes-udagram-reverseproxy
  name: ducta11-kubernetes-udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
        service: ducta11-kubernetes-udagram-reverseproxy
  template:
    metadata:
      labels:
        service: ducta11-kubernetes-udagram-reverseproxy
    spec:
      containers:
      - image: khongthequenbluestar/udacity-udagram-reverseproxy
        name: ducta11-kubernetes-udagram-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "700m"       
        ports:
        - containerPort: 8200
      restartPolicy: Always
